package com.example.y_ogawara.hue_huis

import io.realm.Realm
import io.realm.RealmObject
import io.realm.annotations.Ignore

/**
 * Created by y-ogawara on 17/06/06.
 */


 class HuisData : RealmObject() {

     private var name: String = ""
     private var keyCode: String = ""
     var lightState : String= ""
     var collarR : Int= 0
     var collarG : Int= 0
     var collarB : Int= 0
     var brightness : Int= 0
     var hueId : Int= 0



    // Standard getters & setters generated by your IDE…
    fun getName(): String {
        return name
    }

    fun setName(name: String) {
        this.name = name
    }





    fun getKeyCode(): String {
        return keyCode
    }

    fun setKeyCode(keyCode: String) {
        this.keyCode = keyCode
    }


}
